baseURL = 'https://giacomoettorerocco.com/'
languageCode = 'en-us'
title = 'Zero Bugs Given'
theme = 'PaperMod'
enableRobotsTXT = true

[pagination]
  pagerSize = 5

[params]
  author = 'Giacomo Ettore Rocco'
  description = 'Zero Bugs Given — A roguelite tower defense game'
  defaultTheme = 'dark'
  disableThemeToggle = true
  googleAnalyticsID = 'G-00YJHB8ZF2'
  goatCounterCode = 'giacomoettorerocco'
  showVisitorCount = true

  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = false
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = false
  ShowWordCount = false
  ShowRssButtonInSectionTermList = false
  UseHugoToc = false
  disableSpecial1stPost = true
  disableScrollToTop = false
  comments = false
  hidemeta = true
  hideSummary = false
  showtoc = false
  tocopen = false

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Analytics'
    url = '/zerobugsgiven/'
    weight = 2
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 3

[outputs]
  home = ["HTML", "RSS", "JSON"]
